[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'
hook_add = '''
            let g:user_emmet_settings = {
            \ 'variables' : {
            \  'lang' : "ja"
            \ }
            \}
           '''

[[plugins]]
repo = 'cjrh/vim-conda'
on_ft = 'python'
hook_add = 'let g:jedi#force_py_version = 2'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
build = 'make'
hook_add = "let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'"

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_add = '''
            let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang-6.0.so.1'
            let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
           '''
