[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
            let g:quickrun_config = get(g:, 'quickrun_config', {})
            let g:quickrun_config._ = {
              \ 'runner'    : 'vimproc',
              \ 'runner/vimproc/updatetime' : 60,
              \ 'outputter' : 'error',
              \ 'outputter/error/success' : 'buffer',
              \ 'outputter/error/error'   : 'quickfix',
              \ 'outputter/buffer/split'  : ':rightbelow 8sp',
              \ 'outputter/buffer/close_on_empty' : 1,
              \ }
            let g:quickrun_config['tex'] = { 'command' : 'latexmk',
              \              'exec': ['%c -gg -pdfdvi %s', 'evince %s:r.pdf'],
              \               }
            nnoremap <silent><F5> :QuickRun<CR>
           '''

[[plugins]]
repo = 'w0rp/ale'
