[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'
hook_add = '''
            let g:user_emmet_settings = {
            \ 'variables' : {
            \  'lang' : "ja"
            \ }
            \}
           '''

[[plugins]]
repo = 'cjrh/vim-conda'
on_ft = 'python'
hook_add = 'let g:jedi#force_py_version = 2'
